// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "sentrix.proto" (package "sentrix.v1", syntax proto3)
// tslint:disable
//
// Sentrix gRPC service v0.1 — package sentrix.v1.
//
// Parallel transport to JSON-RPC at port 8545. Same backend, same state,
// different wire format. Methods here mirror the most common JSON-RPC paths
// plus add a server-streaming variant for events that JSON-RPC + WebSocket
// can express but at a higher per-subscriber cost.
//
// Versioning: "sentrix.v1" is a hard contract. Breaking changes go to
// "sentrix.v2" with v1 retained for ≥ 2 minor releases overlap.
//
// Status: v0.1 skeleton. Handlers in crates/sentrix-grpc/src/lib.rs return
// tonic::Status::unimplemented until main.rs integration lands. Reference
// design doc: founder-private/audits/2026-05-05-grpc-service-proto-draft.md.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Sentrix } from "./sentrix.js";
import type { ChainEvent } from "./sentrix.js";
import type { StreamEventsRequest } from "./sentrix.js";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { Mempool } from "./sentrix.js";
import type { GetMempoolRequest } from "./sentrix.js";
import type { Supply } from "./sentrix.js";
import type { GetSupplyRequest } from "./sentrix.js";
import type { ValidatorSet } from "./sentrix.js";
import type { GetValidatorSetRequest } from "./sentrix.js";
import type { Account } from "./sentrix.js";
import type { GetBalanceRequest } from "./sentrix.js";
import type { Block } from "./sentrix.js";
import type { GetBlockRequest } from "./sentrix.js";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BroadcastTxResponse } from "./sentrix.js";
import type { BroadcastTxRequest } from "./sentrix.js";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * ────────────────────────────────────────────────────────────
 * Service definition
 * ────────────────────────────────────────────────────────────
 *
 * @generated from protobuf service sentrix.v1.Sentrix
 */
export interface ISentrixClient {
    /**
     * Submit a signed transaction to the local mempool. Same semantics as
     * JSON-RPC eth_sendRawTransaction for EVM txs, with native fields exposed
     * for staking-ops and other native variants.
     *
     * @generated from protobuf rpc: BroadcastTx
     */
    broadcastTx(input: BroadcastTxRequest, options?: RpcOptions): UnaryCall<BroadcastTxRequest, BroadcastTxResponse>;
    /**
     * Fetch a block by height OR by hash. Returns NOT_FOUND if outside the
     * local chain window (currently 1000 blocks; older blocks need indexer).
     *
     * @generated from protobuf rpc: GetBlock
     */
    getBlock(input: GetBlockRequest, options?: RpcOptions): UnaryCall<GetBlockRequest, Block>;
    /**
     * Fetch account balance + nonce. Mirrors eth_getBalance +
     * eth_getTransactionCount in a single round-trip. Includes mempool-pending
     * nonce so wallets build correct next-tx without an extra call (matches
     * the pending-aware nonce behaviour from chain v2.1.57).
     *
     * @generated from protobuf rpc: GetBalance
     */
    getBalance(input: GetBalanceRequest, options?: RpcOptions): UnaryCall<GetBalanceRequest, Account>;
    /**
     * v0.4 read-only state queries — drop the REST `/sentrix_status_extended`
     * bridge from the explorer's stats hot path. All three are pure reads
     * off `state.read()` snapshots; same lock contention profile as
     * GetBlock/GetBalance.
     *
     * Active validator set + per-validator stake/active/jailed flags.
     *
     * @generated from protobuf rpc: GetValidatorSet
     */
    getValidatorSet(input: GetValidatorSetRequest, options?: RpcOptions): UnaryCall<GetValidatorSetRequest, ValidatorSet>;
    /**
     * Native-token supply snapshot (minted, burned, circulating).
     *
     * @generated from protobuf rpc: GetSupply
     */
    getSupply(input: GetSupplyRequest, options?: RpcOptions): UnaryCall<GetSupplyRequest, Supply>;
    /**
     * Pending-tx count + a capped header window for UI display.
     *
     * @generated from protobuf rpc: GetMempool
     */
    getMempool(input: GetMempoolRequest, options?: RpcOptions): UnaryCall<GetMempoolRequest, Mempool>;
    /**
     * Server-streaming chain events. Subscribe once, receive every event type
     * until cancel or server restart. Replaces N separate eth_subscribe calls.
     * Backpressure: server bounded channel per stream (capacity 4096 — same as
     * event_tx in chain). On slow client, server drops OLDEST events and emits
     * a StreamLagged sentinel. Client should resync state from RPC.
     *
     * @generated from protobuf rpc: StreamEvents
     */
    streamEvents(input: StreamEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamEventsRequest, ChainEvent>;
}
/**
 * ────────────────────────────────────────────────────────────
 * Service definition
 * ────────────────────────────────────────────────────────────
 *
 * @generated from protobuf service sentrix.v1.Sentrix
 */
export class SentrixClient implements ISentrixClient, ServiceInfo {
    typeName = Sentrix.typeName;
    methods = Sentrix.methods;
    options = Sentrix.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Submit a signed transaction to the local mempool. Same semantics as
     * JSON-RPC eth_sendRawTransaction for EVM txs, with native fields exposed
     * for staking-ops and other native variants.
     *
     * @generated from protobuf rpc: BroadcastTx
     */
    broadcastTx(input: BroadcastTxRequest, options?: RpcOptions): UnaryCall<BroadcastTxRequest, BroadcastTxResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<BroadcastTxRequest, BroadcastTxResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Fetch a block by height OR by hash. Returns NOT_FOUND if outside the
     * local chain window (currently 1000 blocks; older blocks need indexer).
     *
     * @generated from protobuf rpc: GetBlock
     */
    getBlock(input: GetBlockRequest, options?: RpcOptions): UnaryCall<GetBlockRequest, Block> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBlockRequest, Block>("unary", this._transport, method, opt, input);
    }
    /**
     * Fetch account balance + nonce. Mirrors eth_getBalance +
     * eth_getTransactionCount in a single round-trip. Includes mempool-pending
     * nonce so wallets build correct next-tx without an extra call (matches
     * the pending-aware nonce behaviour from chain v2.1.57).
     *
     * @generated from protobuf rpc: GetBalance
     */
    getBalance(input: GetBalanceRequest, options?: RpcOptions): UnaryCall<GetBalanceRequest, Account> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBalanceRequest, Account>("unary", this._transport, method, opt, input);
    }
    /**
     * v0.4 read-only state queries — drop the REST `/sentrix_status_extended`
     * bridge from the explorer's stats hot path. All three are pure reads
     * off `state.read()` snapshots; same lock contention profile as
     * GetBlock/GetBalance.
     *
     * Active validator set + per-validator stake/active/jailed flags.
     *
     * @generated from protobuf rpc: GetValidatorSet
     */
    getValidatorSet(input: GetValidatorSetRequest, options?: RpcOptions): UnaryCall<GetValidatorSetRequest, ValidatorSet> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetValidatorSetRequest, ValidatorSet>("unary", this._transport, method, opt, input);
    }
    /**
     * Native-token supply snapshot (minted, burned, circulating).
     *
     * @generated from protobuf rpc: GetSupply
     */
    getSupply(input: GetSupplyRequest, options?: RpcOptions): UnaryCall<GetSupplyRequest, Supply> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSupplyRequest, Supply>("unary", this._transport, method, opt, input);
    }
    /**
     * Pending-tx count + a capped header window for UI display.
     *
     * @generated from protobuf rpc: GetMempool
     */
    getMempool(input: GetMempoolRequest, options?: RpcOptions): UnaryCall<GetMempoolRequest, Mempool> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMempoolRequest, Mempool>("unary", this._transport, method, opt, input);
    }
    /**
     * Server-streaming chain events. Subscribe once, receive every event type
     * until cancel or server restart. Replaces N separate eth_subscribe calls.
     * Backpressure: server bounded channel per stream (capacity 4096 — same as
     * event_tx in chain). On slow client, server drops OLDEST events and emits
     * a StreamLagged sentinel. Client should resync state from RPC.
     *
     * @generated from protobuf rpc: StreamEvents
     */
    streamEvents(input: StreamEventsRequest, options?: RpcOptions): ServerStreamingCall<StreamEventsRequest, ChainEvent> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamEventsRequest, ChainEvent>("serverStreaming", this._transport, method, opt, input);
    }
}
